export const ApiErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  RECURRING_TRANSACTION_NOT_FOUND: 'RECURRING_TRANSACTION_NOT_FOUND',
  BILL_NOT_FOUND: 'BILL_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  HABIT_NOT_FOUND: 'HABIT_NOT_FOUND',
  HABIT_INACTIVE: 'HABIT_INACTIVE',
  HABIT_INVALID_DATE_RANGE: 'HABIT_INVALID_DATE_RANGE',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  BUDGET_ALREADY_EXISTS: 'BUDGET_ALREADY_EXISTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = typeof ApiErrorCodes[keyof typeof ApiErrorCodes];
